homepage: "https://gitlab.com/cryptsetup/cryptsetup"
language: c
primary_contact: "gmazyland@gmail.com"
auto_ccs:
  - okozina@redhat.com
  - vtrefny@redhat.com
  - daniel.zatovic@gmail.com
sanitizers:
  - address
    experimental: True
  - memory:
    experimental: True
 - undefined
    experimental: True
main_repo: "https://gitlab.com/cryptsetup/cryptsetup.git"
